name: intro-bioinfo-python
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.11
    - pip
    - jupyterlab>=4
    - ipywidgets
    - numpy
    - scipy
    - pandas
    - xlrd
    - matplotlib
    - biopython
    - nbdime
    - pip:
        - jupyterquiz
